"""
config/ —— 统一配置中心
"""
from config.settings import (
    DB_PATH, HISTORY_START,
    SYNC_THREADS, SYNC_BATCH_SIZE, SYNC_RETRY_COUNT, SYNC_TIMEOUT,
    FLASK_HOST, FLASK_PORT, FLASK_DEBUG,
    MINING, BACKTEST,
)

from config.thresholds import (
    FUSION_THRESHOLD, FUSION_THRESHOLD_MIN, V4_SCORE_THRESHOLD,
    START_CAPITAL, POSITION_PER_STOCK, POSITION_NUM, SIG_BACKFILL_THRESHOLD,
    STOP_LOSS, TAKE_PROFIT,
    BACKTEST_DEFAULTS, RISK_GUARDS, MARKET_TIMING, DYNAMIC_POSITION,
)

from config.strategy_params import (
    DEFAULT_WEIGHTS, PURE_BOTTOM_WEIGHTS,
    VOLUME_BREAKOUT, MA_CONVERGENCE, PRICE_VOLUME_DIVERGENCE,
    BOTTOM_FISHING, WHALE_ACCUMULATION,
    OVERSOLD_REBOUND_V4, V4_PARAM_GRID,
    get_strategy_params,
)

__all__ = [
    "DB_PATH", "HISTORY_START",
    "SYNC_THREADS", "SYNC_BATCH_SIZE", "SYNC_RETRY_COUNT", "SYNC_TIMEOUT",
    "FLASK_HOST", "FLASK_PORT", "FLASK_DEBUG",
    "MINING", "BACKTEST",
    "FUSION_THRESHOLD", "FUSION_THRESHOLD_MIN", "V4_SCORE_THRESHOLD",
    "START_CAPITAL", "POSITION_PER_STOCK", "POSITION_NUM", "SIG_BACKFILL_THRESHOLD",
    "STOP_LOSS", "TAKE_PROFIT",
    "BACKTEST_DEFAULTS", "RISK_GUARDS", "MARKET_TIMING", "DYNAMIC_POSITION",
    "DEFAULT_WEIGHTS", "PURE_BOTTOM_WEIGHTS",
    "VOLUME_BREAKOUT", "MA_CONVERGENCE", "PRICE_VOLUME_DIVERGENCE",
    "BOTTOM_FISHING", "WHALE_ACCUMULATION",
    "OVERSOLD_REBOUND_V4", "V4_PARAM_GRID",
    "get_strategy_params",
]
