"""
config/ —— 统一配置中心

所有策略参数、阈值、费率和调度时间集中管理。
Agent 和策略模块应从这里导入配置，不再硬编码。
"""

from config.settings import (
    DB_PATH, API_HOST, API_PORT, API_DEBUG,
    SCHEDULE_SYNC_TIME, SCHEDULE_SCAN_TIME,
    SYNC_BATCH_SIZE, SYNC_VERBOSE, LOG_LEVEL,
)

from config.thresholds import (
    FUSION_THRESHOLD, FUSION_THRESHOLD_MIN, V4_SCORE_THRESHOLD,
    START_CAPITAL, POSITION_PER_STOCK, POSITION_NUM, SIG_BACKFILL_THRESHOLD,
    STOP_LOSS, TAKE_PROFIT,
    BACKTEST_DEFAULTS, RISK_GUARDS, MARKET_TIMING, DYNAMIC_POSITION,
)

from config.strategy_params import (
    DEFAULT_WEIGHTS, PURE_BOTTOM_WEIGHTS,
    VOLUME_BREAKOUT, MA_CONVERGENCE, PRICE_VOLUME_DIVERGENCE,
    BOTTOM_FISHING, WHALE_ACCUMULATION,
    OVERSOLD_REBOUND_V4, V4_PARAM_GRID,
    get_strategy_params,
)

__all__ = [
    "DB_PATH", "API_HOST", "API_PORT", "API_DEBUG",
    "SCHEDULE_SYNC_TIME", "SCHEDULE_SCAN_TIME",
    "SYNC_BATCH_SIZE", "SYNC_VERBOSE", "LOG_LEVEL",
    "FUSION_THRESHOLD", "FUSION_THRESHOLD_MIN", "V4_SCORE_THRESHOLD",
    "START_CAPITAL", "POSITION_PER_STOCK", "POSITION_NUM", "SIG_BACKFILL_THRESHOLD",
    "STOP_LOSS", "TAKE_PROFIT",
    "BACKTEST_DEFAULTS", "RISK_GUARDS", "MARKET_TIMING", "DYNAMIC_POSITION",
    "DEFAULT_WEIGHTS", "PURE_BOTTOM_WEIGHTS",
    "VOLUME_BREAKOUT", "MA_CONVERGENCE", "PRICE_VOLUME_DIVERGENCE",
    "BOTTOM_FISHING", "WHALE_ACCUMULATION",
    "OVERSOLD_REBOUND_V4", "V4_PARAM_GRID",
    "get_strategy_params",
]
